### ISSUE TITLE
the original link in the paper does not work

### ISSUE THREAD

**Issue by aakhmetz** [benjisamschlu/Subnational-covid19#1]
Hello, just noting, that the original link in the paper seems to be wrong: https://github.com/benjisamschlu/Subnationalcovid19
(see https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-022-00874-7)

**Comment by benjisamschlu** [comment]
Hello Andrei,
Thank you for letting me know... That is a shame!
I will ask for a correction of the link in the online version.

**Comment by aakhmetz** [comment]
I remember that github redirects automatically when the repo is renamed. I wonder if renaming it to "Subnationalcovid19" and then back to "Subnational-covid19" would do the trick (also I am not sure)

**Comment by benjisamschlu** [comment]
This might be a nice trick if the journal does not allow any modification!
Thank you so much!

**Comment by aakhmetz** [comment]
As I remember, no changes are allowed after the proof. But github may be more flexible.

ps: Thank you for a nice work! I will study!

**Comment by benjisamschlu** [comment]
I just did the modification in repo's name so the link works now!
Thank you for pointing that out!
Best,
